<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesseurRepository extends EntityRepository
{
  public function getMatieres($id){
    $qb = $this->createQueryBuilder('a')
    ->where('a.id = :id')
    ->setParameter('id', $id)
    ->leftJoin('a.prof_matieres' ,'pm')
    ->addSelect('pm')
    ->leftJoin('pm.matiere','m')
    ->addSelect('m');
    return $qb->getQuery()->getResult();
  }
}
