<?php

namespace EDTBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfMatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfMatiereRepository extends EntityRepository
{
  public function getNomsProfsMatieres(){
        $qb = $this->createQueryBuilder('pm')
        ->leftJoin('pm.professeur' ,'p')
        ->addSelect('p.username')
        ->leftJoin('pm.matiere', 'm')
        ->addSelect('m.nom');
        return $qb->getQuery()->getResult();
  }
}
