<?php

namespace EDTBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EDTBUndle\Entity\Type;

/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends EntityRepository
{
  function getSallesCorrespondantes($id_type){
    $qb = $this->createQueryBuilder('salles')
          ->leftJoin('salles.type' , 'type')
          ->where('type.id = :id_type')
          ->setParameter('id_type', $id_type);
    return $qb->getQuery()->getResult();
  }
}
