<?php

namespace EDTBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends EntityRepository
{
}
