
admin_home_page:
    path: /
    defaults: { _controller: EDTBundle:Admin:index}


# route generique aux users Professuer et Utilisateur
edt_user_view:
    path:   /view/user/{entite}
    defaults: {_controller: EDTBundle:Admin:afficherUser }
    requirements:
      entite: 'Etudiant|Professeur'

# route perso à une entite
edt_ProfMatiere_view:
    path:   /view/ProfMatiere
    defaults: {_controller: EDTBundle:Admin:afficherProfMatiere}

edt_Matiere_view:
    path:   /view/Matiere
    defaults: {_controller: EDTBundle:Admin:afficherMatiere }

edt_Matiere_add:
    path:  /add/Matiere
    defaults: {_controller: EDTBundle:Admin:ajouterMatiere}

#route generique aux Entites Salle MAtiere, ....

edt_entite_view:
    path:    /view/{entite}
    defaults: {_controller: EDTBundle:Admin:afficherEntite}



# route spécifique à chaque entité pour ajouter/modofier
# SALLE
edt_Salle_edit:
    path:   /edit/Salle/{id}
    defaults: {_controller: EDTBundle:Admin:editerSalle}
    requirements:
        id : \d+

edt_Salle_add:
    path:   /add/Salle
    defaults: {_controller: EDTBundle:Admin:ajouterSalle}

#route generique à toutes les entités
edt_entite_delete:
    path:   /{entite}/delete/{id}
    defaults: {_controller: EDTBundle:Admin:deleteEntite}
    requirements:
      id : \d+
      entite: 'Salle|Matiere|Etudiant|Professeur|ProfMatiere|Type'

edt_entite_add:
    path:  /add/{entite}
    defaults: {_controller: EDTBundle:Admin:addEntite}
    requirements:
      entite: 'Salle|Matiere|Etudiant|Professeur|ProfMatiere|Type'

edt_entite_edit:
    path: /edit/{entite}/{id}
    defaults: {_controller: EDTBundle:Admin:editEntite}
    requirements:
        id: \d+
        entite: 'Salle|Matiere|ProfMatiere|Type'

# MATIERE
edt_Matiere_edit:
    path:   /edit/Matiere/{id}
    defaults: {_controller: EDTBundle:Admin:editerMatiere}

edt_Matiere_add:
    path:  /edit/Matiere
    defaults: {_controller: EDTBundle:Admin:ajouterMatiere}
# PROF MATIERE
edt_ProfMatiere_add:
    path:  /add/ProfMatiere
    defaults: {_controller: EDTBundle:Admin:ajouter}

#route pour les maj de USERs
edt_user_edit:
    path:     /edit/user/{entite}/{id}
    defaults: {_controller:  EDTBundle:Admin:editUser}
    requirements:
      id : \d+

edt_user_add:
    path:   /add/user/{entite}
    defaults: {_controller: EDTBundle:Admin:addUser}


edt_afficherCours:
    path:   /afficherMesCours
    defaults: {_controller: EDTBundle:Admin:afficherMesCours}
