
admin_home_page:
    path: /
    defaults: { _controller: EDTBundle:Admin:index}


# route generique aux users Professuer et Utilisateur
edt_user_view:
    path:   /view/user/{entite}
    defaults: {_controller: EDTBundle:Admin:afficherUser }
    requirements:
      entite: 'Etudiant|Professeur'
#route generique aux Entites Salle MAtiere, ....
edt_entite_view:
    path:    /view/{entite}
    defaults: {_controller: EDTBundle:Admin:afficherEntite}

#route generique à toutes les entités
edt_entite_delete:
    path:   /{entite}/delete/{id}
    defaults: {_controller: EDTBundle:Admin:deleteEntite}
    requirements:
      id : \d+
      entite: 'Salle|Matiere|Etudiant|Professeur'

# route spécifique à chaque entité pour ajouter/modofier
edt_Salle_edit:
    path:   /edit/Salle/{id}
    defaults: {_controller: EDTBundle:Admin:editerSalle}
    requirements:
        id : \d+

edt_Salle_add:
    path:   /add/Salle
    defaults: {_controller: EDTBundle:Admin:ajouterSalle}


#route pour les maj de USERs
edt_user_edit:
    path:     /edit/user/{entite}/{id}
    defaults: {_controller:  EDTBundle:Admin:editUser}
    requirements:
      id : \d+

edt_user_add:
    path:   /add/user/{entite}
    defaults: {_controller: EDTBundle:Admin:addUser}
