
admin_home_page:
    path: /
    defaults: { _controller: EDTBundle:Admin:index}


# route generique aux users Professuer et Utilisateur
edt_user_view:
    path:   /view/user/{entite}
    defaults: {_controller: EDTBundle:Admin:afficherUser }
    requirements:
      entite: 'Etudiant|Professeur'

# route perso à une entite
edt_ProfMatiere_view:
    path:   /view/ProfMatiere
    defaults: {_controller: EDTBundle:Admin:afficherProfMatiere}

edt_Matiere_view:
    path:   /view/Matiere
    defaults: {_controller: EDTBundle:Admin:afficherMatiere }

edt_Matiere_add:
    path:  /add/Matiere
    defaults: {_controller: EDTBundle:Admin:ajouterMatiere}

edt_Groupe_add:
    path: /add/Groupe
    defaults: {_controller: EDTBundle:Admin:ajouterGroupe}

#route generique aux Entites Salle MAtiere, ....

edt_entite_view:
    path:    /view/{entite}
    defaults: {_controller: EDTBundle:Admin:afficherEntite}

#------------------------------------------------------------------
# route pour Evenement
edt_Evenement_add :
    path: /add/Evenement
    defaults: {_controller: EDTBundle:Admin:ajouterEvenement}

#route pour la requete ajax:
type_ajax_call:
    path: /ajax/type
    defaults: {_controller: EDTBundle:Admin:ajaxType}

matiere_ajax_call:
    path: /ajax/matiere
    defaults: {_controller: EDTBundle:Admin:ajaxMatiere}

# PROF MATIERE
edt_ProfMatiere_add:
    path:  /add/ProfMatiere
    defaults: {_controller: EDTBundle:Admin:ajouterProfMatiere}
#------------------------------------------------------------------------


# route spécifique à chaque entité pour ajouter/modofier
# SALLE
edt_Salle_edit:
    path:   /edit/Salle/{id}
    defaults: {_controller: EDTBundle:Admin:editerSalle}
    requirements:
        id : \d+

edt_Matiere_edit:
    path:   /edit/Matiere/{id}
    defaults: {_controller: EDTBundle:Admin:editerMatiere}
    requirements:
        id : \d+

edt_Evenement_edit:
    path:   /edit/Evenement/{id}
    defaults: {_controller: EDTBundle:Admin:editerEvenement}
    requirements:
        id : \d+

edt_Etudiant_edit:
    path:   /edit/Etudiant/{id}
    defaults: {_controller: EDTBundle:Admin:editerEtudiant}
    requirements:
        id : \d+

edt_Type_edit:
    path:   /edit/Type/{id}
    defaults: {_controller: EDTBundle:Admin:editerType}
    requirements:
        id : \d+

edt_Salle_add:
    path:   /add/Salle
    defaults: {_controller: EDTBundle:Admin:ajouterSalle}

edt_Groupe_edit:
    path:   /edit/Groupe/{id}
    defaults: {_controller: EDTBundle:Admin:editerGroupe}
    requirements:
        id : \d+

#route generique à toutes les entités
edt_entite_delete:
    path:   /{entite}/delete/{id}
    defaults: {_controller: EDTBundle:Admin:deleteEntite}
    requirements:
      id : \d+
      entite: 'Salle|Matiere|Etudiant|Professeur|ProfMatiere|Type|Groupe|Evenement'

edt_entite_add:
    path:  /add/{entite}
    defaults: {_controller: EDTBundle:Admin:addEntite}
    requirements:
      entite: 'Salle|Matiere|Etudiant|Professeur|ProfMatiere|Type|Groupe|Evenement'

edt_entite_edit:
    path: /edit/{entite}/{id}
    defaults: {_controller: EDTBundle:Admin:editEntite}
    requirements:
        id: \d+
        entite: 'Salle|Matiere|ProfMatiere|Type|Groupe|Evenement'

# MATIERE
edt_Matiere_edit:
    path:   /edit/Matiere/{id}
    defaults: {_controller: EDTBundle:Admin:editerMatiere}

edt_Matiere_add:
    path:  /edit/Matiere
    defaults: {_controller: EDTBundle:Admin:ajouterMatiere}

#route pour les maj de USERs
edt_user_edit:
    path:     /edit/user/{entite}/{id}
    defaults: {_controller:  EDTBundle:Admin:editUser}
    requirements:
      id : \d+

edt_user_add:
    path:   /add/user/{entite}
    defaults: {_controller: EDTBundle:Admin:addUser}


edt_afficherCours:
    path:   /afficherMesCours
    defaults: {_controller: EDTBundle:Admin:afficherMesCours}
