services:
#    edt.example:
#        class: EDTBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

# acme.demobundle.calendar_listener:
#   class: Acme\DemoBundle\EventListener\CalendarEventListener
#   arguments: ["doctrine.orm.entity_manager", ]

# <service id="acme.demobundle.calendar_listener" class="Acme\DemoBundle\EventListener\CalendarEventListener">
#     <argument type="service" id="doctrine.orm.entity_manager" />
#     <tag name="kernel.event_listener" event="calendar.load_events" method="loadEvents" />
# </service>